# projectReferences:
#   IJKMediaPlayer:
#     path: modules/ijkplayer/ios/IJKMediaPlayer/IJKMediaPlayer.xcodeproj

targetTemplates:
  uAppBase:
    settings:
      DEVELOPMENT_TEAM: 3DSM494K6L

    dependencies:
      - framework: SDKs/SDK/libs//libWeChatSDK.a
        embed: false
      - framework: SDKs/SDK/libs/IJKMediaFrameworkWithSSL.framework
        embed: false
      # - framework: IJKMediaFrameworkWithSSL.framework
      #   implicit: true
      #   embed: true